---
- name: kube-master
  box: roboxes/ubuntu2004
  hostname: kube-master
  ipaddress: 172.16.1.100
  memory: 4096
  cpus: 2
  provision: "kube-master.yaml"

- name: kube-node1
  box: roboxes/ubuntu2004
  hostname: kube-node1
  ipaddress: 172.16.1.101
  memory: 2560
  cpus: 2
  provision: "kube-node1.yaml"

- name: kube-node2
  box: roboxes/ubuntu2004
  hostname: kube-node2
  ipaddress: 172.16.1.102
  memory: 2560
  cpus: 2
  provision: "kube-node2.yaml"

- name: kube-infra
  box: roboxes/ubuntu2004
  hostname: kube-infra
  ipaddress: 172.16.1.103
  memory: 2048
  cpus: 2
  provision: "kube-infra.yaml"

